[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "<YOUR_PROGRAM_ID_HERE>"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/halfgork/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
